import Navber from "@/app/components/Navber";
import Footer from "@/app/components/Footer";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import clsx from "clsx";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "BuzzlyShop",
  description: "Generated by BuzzlyShop",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(poppins.className, "bg-light text-dark")}>
        <Navber />
        {children}
        <Footer />
      </body>
    </html>
  );
}
